package:
  format-version: "1.0.0"
  name: "core_apps_sam_d5x_e5x"
  version: "v3.4.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.17.0"
    - name: "dev_packs"
      type: "package"
      version: "v3.17.0"
    - name: "core"
      type: "package"
      version: "v3.13.0"
    - name: "usb"
      type: "package"
      version: "v3.10.0"
    - name: "littlefs"
      type: "package"
      version: "v2.5.1"
    - name: "filex"
      type: "package"
      version: "v6.2.1_rel"